# Generated by Django 4.2.7 on 2026-05-07 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsing_error', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_uploads', to='core.student')),
            ],
            options={
                'db_table': 'resume_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BuiltResume',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Tech Company ATS', 'Product Manager', 'One-Pager'", max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('canonical_json', models.JSONField(default=dict, help_text='Canonical resume format — all operations use this.')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('generated', 'Generated'), ('active', 'Active'), ('archived', 'Archived'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error reason if state=failed.')),
                ('is_primary', models.BooleanField(default=False, help_text='Default resume shown to employers.')),
                ('generated_pdf', models.FileField(blank=True, help_text='Cached PDF. Can be regenerated from canonical_json.', null=True, upload_to='resumes/generated/%Y/%m/')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_resumes', to='core.student')),
            ],
            options={
                'db_table': 'built_resumes',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
