# Generated by Django 4.2.7 on 2026-05-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_engine', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtresume',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='templates_engine.resumetemplate'),
        ),
        migrations.AddIndex(
            model_name='resumeupload',
            index=models.Index(fields=['student', 'uploaded_at'], name='resume_uplo_student_ba7984_idx'),
        ),
        migrations.AddIndex(
            model_name='builtresume',
            index=models.Index(fields=['student', 'is_primary', 'state'], name='built_resum_student_19c569_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='builtresume',
            unique_together={('student', 'title')},
        ),
    ]
