# Generated by Django 4.2.7 on 2026-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtresume',
            name='custom_html',
            field=models.TextField(blank=True, help_text='If provided, this HTML is used directly to generate the PDF instead of canonical_json.', null=True),
        ),
    ]
