# Generated by Django 4.2.7 on 2026-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_builtresume_custom_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeupload',
            options={'ordering': ['-is_primary', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Default resume shown to employers.'),
        ),
    ]
