# Generated by Django 4.2.7 on 2026-07-22 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resumeupload_options_resumeupload_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtresume',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Cached PDF. Can be regenerated from canonical_json.', max_length=255, null=True, upload_to='resumes/generated/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='file',
            field=models.FileField(max_length=255, upload_to='resumes/uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
