# Generated by Django 4.2.7 on 2026-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_job_alerts',
            field=models.BooleanField(default=True, help_text='Receive transactional email alerts for eligible jobs.'),
        ),
    ]
