# Generated by Django 4.2.7 on 2026-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Soft Skill', 'Soft Skill'), ('Language', 'Language'), ('Other', 'Other')], default='Technical', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=20),
        ),
    ]
