# Generated by Django 4.2.7 on 2026-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_skill_category_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile photo.', null=True, upload_to='profile_pictures/'),
        ),
    ]
