# Generated by Django 4.2.7 on 2026-07-08 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_studentprofile_email_job_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='languages_known',
            field=models.JSONField(blank=True, default=list, help_text='List of languages known.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='List of student strengths.'),
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracurricular_activities', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'student_extracurricular_activities',
                'ordering': ['-date'],
            },
        ),
    ]
