# Generated by Django 4.2.7 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_studentprofile_languages_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile photo.', max_length=255, null=True, upload_to='profile_pictures/'),
        ),
    ]
