# Generated by Django 4.2.7 on 2026-07-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
