# Generated by Django 4.2.7 on 2026-05-14 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)])),
                ('mastery_keywords', models.JSONField(default=list)),
                ('learning_resources', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_competencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_domains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.IntegerField(default=30)),
                ('questions_per_session', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_types', to='interviews.interviewdomain')),
            ],
            options={
                'db_table': 'interview_types',
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(choices=[('4_weeks', '4 Weeks'), ('8_weeks', '8 Weeks'), ('12_weeks', '12 Weeks')], default='8_weeks', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('milestones_structure', models.JSONField(default=list)),
                ('total_hours', models.IntegerField(default=40)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_templates', to='interviews.interviewdomain')),
            ],
            options={
                'db_table': 'roadmap_templates',
                'ordering': ['domain', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_skills', models.JSONField(default=dict)),
                ('skill_gaps', models.JSONField(default=list)),
                ('competency_gaps', models.JSONField(default=dict)),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gap_analyses', to='interviews.interviewdomain')),
                ('recommended_roadmap_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='interviews.roadmaptemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to='core.student')),
            ],
            options={
                'db_table': 'skill_gap_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestones', models.JSONField(default=list)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_completion_date', models.DateField()),
                ('total_hours', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gap_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='interviews.skillgapanalysis')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_roadmaps', to='core.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='interviews.roadmaptemplate')),
            ],
            options={
                'db_table': 'quick_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('short_answer', 'Short Answer'), ('essay', 'Essay'), ('coding', 'Coding Problem'), ('interview', 'Interview Question'), ('scenario', 'Scenario Handling')], default='interview', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('expected_keywords', models.JSONField(default=dict)),
                ('expected_answer_summary', models.TextField(blank=True, default='')),
                ('scoring_rubric', models.JSONField(default=dict)),
                ('max_score', models.IntegerField(default=100)),
                ('follow_up_questions', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, default='internal', max_length=100)),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.competency')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['difficulty_level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('questions', models.JSONField(default=list)),
                ('use_voice', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='interviews.interviewtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='core.student')),
            ],
            options={
                'db_table': 'mock_interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.FloatField()),
                ('competency_scores', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('feedback_summary', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'interview_feedback',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('eval_status', models.CharField(choices=[('submitted', 'Submitted'), ('scored', 'Scored'), ('reviewed', 'Manually Reviewed')], default='submitted', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100)),
                ('keywords_found', models.JSONField(default=list)),
                ('keywords_missing', models.JSONField(default=list)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('auto_feedback', models.TextField(blank=True, default='')),
                ('ai_reviewed', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='interviews.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'interview_answers',
                'ordering': ['question_number'],
            },
        ),
        migrations.AddField(
            model_name='competency',
            name='interview_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='interviews.interviewtype'),
        ),
        migrations.AddIndex(
            model_name='skillgapanalysis',
            index=models.Index(fields=['student', '-analyzed_at'], name='skill_gap_a_student_0aa561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmaptemplate',
            unique_together={('domain', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['competency', 'difficulty_level'], name='interview_q_compete_bdf417_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='interview_q_questio_e42944_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'difficulty_level'], name='interview_q_is_acti_6e3c95_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['student', 'status'], name='mock_interv_student_af3853_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['student', '-created_at'], name='mock_interv_student_c8967a_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewanswer',
            index=models.Index(fields=['session', 'question_number'], name='interview_a_session_637e64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('interview_type', 'name')},
        ),
    ]
