# Generated by Django 4.2.7 on 2026-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_rename_score_breakdown_interviewanswer_evaluation_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('pending_review', 'Pending Manual Review')], default='scheduled', max_length=20),
        ),
    ]
