# Generated by Django 4.2.7 on 2026-05-18 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'career_profiles',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'career_courses',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='career_os.careerprofile')),
            ],
            options={
                'db_table': 'career_roadmaps',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'career_skills',
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='career_os.careerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_os.skill')),
            ],
            options={
                'db_table': 'career_student_skills',
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('duration_weeks', models.IntegerField()),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='career_os.roadmap')),
            ],
            options={
                'db_table': 'career_roadmap_phases',
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='PhaseSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_level', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_learn', to='career_os.roadmapphase')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_os.skill')),
            ],
            options={
                'db_table': 'career_phase_skills',
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_hours', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='career_os.skill')),
            ],
            options={
                'db_table': 'career_learning_resources',
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='career_os.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_os.skill')),
            ],
            options={
                'db_table': 'career_course_skills',
            },
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_os.course'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to='core.student'),
        ),
    ]
