# Generated by Django 4.2.7 on 2026-05-18 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career_os', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roadmap', models.JSONField(default=dict)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roadmaps', to='career_os.careerprofile')),
            ],
            options={
                'db_table': 'career_ai_roadmaps',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gaps', models.JSONField(default=list)),
                ('motivation', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='career_os.careerprofile')),
            ],
            options={
                'db_table': 'career_ai_analyses',
            },
        ),
    ]
