# Generated by Django 4.2.7 on 2026-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_os', '0002_airoadmap_aianalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airoadmap',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
        migrations.DeleteModel(
            name='AIRoadmap',
        ),
    ]
