# Generated by Django 4.2.7 on 2026-06-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseJobFeedCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('job_ids', models.JSONField(default=list)),
                ('internship_ids', models.JSONField(default=list)),
                ('scraping_run_id', models.IntegerField(blank=True, null=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('total_internships', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_job_feed_cache',
            },
        ),
        migrations.CreateModel(
            name='CourseSearchConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(default=list)),
                ('internship_keywords', models.JSONField(default=list)),
                ('exclude_keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'course_search_configs',
                'ordering': ['priority', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('jsearch', 'JSearch'), ('adzuna', 'Adzuna'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=300)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_short', models.CharField(blank=True, max_length=500, null=True)),
                ('apply_url', models.URLField(max_length=1000)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, default='INR', max_length=10, null=True)),
                ('salary_display', models.CharField(blank=True, max_length=200, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('experience_required', models.CharField(blank=True, max_length=100, null=True)),
                ('is_internship', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('raw_data', models.JSONField(default=dict)),
                ('dedup_hash', models.CharField(max_length=64, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved jobs are shown to students in their job feed.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraped_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scraped_jobs',
            },
        ),
        migrations.CreateModel(
            name='ScrapingRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                ('total_fetched', models.IntegerField(default=0)),
                ('total_saved', models.IntegerField(default=0)),
                ('total_duplicates_skipped', models.IntegerField(default=0)),
                ('total_expired_deactivated', models.IntegerField(default=0)),
                ('courses_completed', models.JSONField(default=list)),
                ('courses_failed', models.JSONField(default=list)),
                ('per_course_stats', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('api_calls_made', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'scraping_runs',
            },
        ),
        migrations.CreateModel(
            name='ScraperHealthMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('pool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('jobs_fetched', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('actual_api_calls', models.IntegerField(default=0)),
                ('is_healthy', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('scraping_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='scraped_jobs.scrapingrun')),
            ],
            options={
                'db_table': 'scraper_health_metrics',
            },
        ),
        migrations.CreateModel(
            name='FailedScrapeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('pool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_snippet', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('failure_type', models.CharField(choices=[('parse_error', 'Parse Error'), ('validation_error', 'Validation Error'), ('dedup_error', 'Dedup Error'), ('save_error', 'Save Error')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('scraping_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='scraped_jobs.scrapingrun')),
            ],
            options={
                'db_table': 'failed_scrape_records',
            },
        ),
        migrations.CreateModel(
            name='CourseJobMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='scraped_jobs.scrapedjob')),
            ],
            options={
                'db_table': 'course_job_mappings',
            },
        ),
        migrations.CreateModel(
            name='StudentSavedJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scraped_jobs.scrapedjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='core.student')),
            ],
            options={
                'db_table': 'student_saved_jobs',
                'indexes': [models.Index(fields=['student', '-saved_at'], name='student_sav_student_45caef_idx')],
                'unique_together': {('student', 'scraped_job')},
            },
        ),
        migrations.CreateModel(
            name='StudentJobView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraped_jobs.scrapedjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='core.student')),
            ],
            options={
                'db_table': 'student_job_views',
                'indexes': [models.Index(fields=['student', '-viewed_at'], name='student_job_student_0cba51_idx')],
                'unique_together': {('student', 'scraped_job')},
            },
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['is_active', '-scraped_at'], name='scraped_job_is_acti_c213cf_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['source', 'posted_at'], name='scraped_job_source_8b6429_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['company_name'], name='scraped_job_company_5f2316_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['dedup_hash'], name='scraped_job_dedup_h_ed20c7_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['source', 'external_job_id'], name='scraped_job_source_7523d7_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['scraped_at'], name='scraped_job_scraped_3143ae_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['expires_at'], name='scraped_job_expires_3b4117_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['is_active'], name='scraped_job_is_acti_9fcb83_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['job_type'], name='scraped_job_job_typ_fad3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['is_internship'], name='scraped_job_is_inte_58303f_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['-quality_score', '-scraped_at'], name='scraped_job_quality_6bfb27_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['is_approved', '-scraped_at'], name='scraped_job_is_appr_20d690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedjob',
            unique_together={('external_job_id', 'source')},
        ),
        migrations.AddIndex(
            model_name='coursejobmapping',
            index=models.Index(fields=['course_name', 'scraped_job'], name='course_job__course__f0a659_idx'),
        ),
        migrations.AddIndex(
            model_name='coursejobmapping',
            index=models.Index(fields=['course_name'], name='course_job__course__9415b1_idx'),
        ),
        migrations.AddIndex(
            model_name='coursejobmapping',
            index=models.Index(fields=['course_name', 'scraped_at'], name='course_job__course__c1863d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursejobmapping',
            unique_together={('course_name', 'scraped_job')},
        ),
    ]
