# Generated by Django 4.2.7 on 2026-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraped_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesearchconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scrapedjob',
            name='job_type',
            field=models.CharField(choices=[('fresher_job', 'Fresher Job'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
    ]
