# Generated by Django 4.2.7 on 2026-05-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraped_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedjob',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraped_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved jobs are shown to students in their job feed.'),
        ),
        migrations.AddIndex(
            model_name='scrapedjob',
            index=models.Index(fields=['is_approved', '-scraped_at'], name='scraped_job_is_appr_20d690_idx'),
        ),
    ]
