# Generated by Django 4.2.7 on 2026-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraped_jobs', '0002_add_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedjob',
            name='source',
            field=models.CharField(choices=[('jsearch', 'JSearch'), ('adzuna', 'Adzuna'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
