# Generated by Django 5.0.6 on 2026-06-27 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('session_type', models.CharField(choices=[('orientation', 'Orientation'), ('company_talk', 'Company Talk'), ('interview_prep', 'Interview Prep'), ('aptitude', 'Aptitude Training'), ('resume', 'Resume Workshop'), ('general', 'General Session')], default='general', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('target_courses', models.JSONField(blank=True, default=list)),
                ('target_streams', models.JSONField(blank=True, default=list)),
                ('target_years', models.JSONField(blank=True, default=list)),
                ('zoom_meeting_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoom_join_url', models.URLField(blank=True, default='')),
                ('zoom_start_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_placement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_email', models.EmailField(max_length=254)),
                ('participant_name', models.CharField(blank=True, default='', max_length=200)),
                ('event_type', models.CharField(choices=[('join', 'Join'), ('leave', 'Leave')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='placement_sessions.placementsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_session_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_session_events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_count', models.IntegerField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('attendance_percent', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('marked_via', models.CharField(choices=[('zoom_auto', 'Zoom Auto'), ('manual', 'Manual Override')], default='zoom_auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_session_marks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='placement_sessions.placementsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_session_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement_session_attendance',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
