# Generated by Django 4.2.7 on 2026-07-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementsession',
            name='zoom_join_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='zoom_start_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
