# Generated by Django 4.2.7 on 2026-06-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('html_template', models.TextField(help_text='Jinja2/Django template HTML')),
                ('css_styles', models.TextField(help_text='CSS styles for the template')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Template',
                'db_table': 'resume_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSnapshot',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_snapshot', models.JSONField(help_text='Full template state (HTML+CSS) frozen at snapshot time.')),
                ('rendered_html', models.TextField(help_text='Fully rendered HTML output at snapshot time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('built_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='resumes.builtresume')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='templates_engine.resumetemplate')),
            ],
            options={
                'verbose_name': 'Resume Snapshot',
                'db_table': 'resume_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['is_active', 'created_at'], name='resume_temp_is_acti_ce7a89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumetemplate',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='resumesnapshot',
            index=models.Index(fields=['built_resume', 'created_at'], name='resume_snap_built_r_40bef7_idx'),
        ),
    ]
