# Generated by Django 4.2.7 on 2026-05-07 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('resume_created', 'Resume Created'), ('resume_generated', 'Resume Generated'), ('resume_updated', 'Resume Updated'), ('resume_deleted', 'Resume Deleted'), ('resume_downloaded', 'Resume Downloaded'), ('resume_state_changed', 'Resume State Changed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_versioned', 'Template Version Created'), ('profile_updated', 'Profile Updated'), ('upload_processed', 'Upload Processed'), ('upload_failed', 'Upload Failed'), ('ai_enhancement', 'AI Enhancement Applied')], max_length=50)),
                ('resource_type', models.CharField(choices=[('resume', 'Resume'), ('template', 'Template'), ('profile', 'Profile'), ('upload', 'Upload')], max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Audit Log',
                'verbose_name_plural': 'Resume Audit Logs',
                'db_table': 'resume_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action', 'created_at'], name='resume_audi_actor_i_42a5db_idx'), models.Index(fields=['resource_type', 'resource_id'], name='resume_audi_resourc_1e9139_idx')],
            },
        ),
    ]
