# Generated by Django 4.2.7 on 2026-06-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resumeauditlog',
            index=models.Index(fields=['actor', 'action', 'created_at'], name='resume_audi_actor_i_42a5db_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='resume_audi_resourc_1e9139_idx'),
        ),
    ]
