# Generated by Django 4.2.7 on 2026-06-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NorthStarAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='north_star/assignments/')),
                ('due_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('max_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('zoom_meeting_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoom_join_url', models.URLField(blank=True, default='')),
                ('zoom_start_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course')),
                ('courses', models.ManyToManyField(blank=True, related_name='scheduled_classes', to='core.course')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NorthStarQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='north_star.northstarassignment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_email', models.EmailField(max_length=254)),
                ('participant_name', models.CharField(blank=True, default='', max_length=200)),
                ('event_type', models.CharField(choices=[('join', 'Join'), ('leave', 'Leave')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('scheduled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='north_star.scheduledclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percent', models.FloatField(default=0)),
                ('attendance_percent', models.FloatField(default=0)),
                ('certificate_unlocked', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('join_count', models.IntegerField(default=0)),
                ('marked_via', models.CharField(choices=[('zoom_auto', 'Zoom Auto'), ('manual', 'Manual Override')], default='zoom_auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('scheduled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='north_star.scheduledclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('scheduled_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='north_star/submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('answers_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='north_star.northstarassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
