# Generated by Django 4.2.7 on 2026-06-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('listing_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='job', max_length=20)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('Own', 'Own Category')], default='C', max_length=10)),
                ('openings_count', models.IntegerField(default=1)),
                ('hr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('eligibility_rules', models.JSONField(default=dict)),
                ('application_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('round_name', models.CharField(max_length=255)),
                ('round_type', models.CharField(choices=[('test', 'Test'), ('interview', 'Interview'), ('group_discussion', 'Group Discussion'), ('assignment', 'Assignment')], max_length=50)),
                ('is_elimination', models.BooleanField(default=True)),
                ('passing_score', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='jobs.job')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('job', 'round_number')},
            },
        ),
    ]
