# Generated by Django 5.1.4 on 2026-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='listing_type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='job', max_length=20),
        ),
    ]
