# Generated by Django 5.0.6 on 2026-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobround',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobround',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='jobround',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('job', 'round_number'), name='unique_active_round_number'),
        ),
    ]
