# Generated by Django 4.2.7 on 2026-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_listing_type_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
