# Generated by Django 5.0.6 on 2026-07-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobround_unique_together_jobround_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.CharField(max_length=255),
        ),
    ]
