# Generated by Django 4.2.7 on 2026-08-19 11:18

from django.db import migrations, models

def populate_job_ids(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    jobs = Job.objects.all().order_by('created_at')
    for index, job in enumerate(jobs, start=1):
        job.job_id = index
        job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_job_ids, reverse_code=migrations.RunPython.noop),
    ]
