# Generated by Django 4.2.7 on 2026-05-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='openings_count',
            field=models.IntegerField(default=1),
        ),
    ]
