# Generated by Django 4.2.7 on 2026-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_category_job_openings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
