# Generated by Django 4.2.7 on 2026-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_hr_email_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
