# Generated by Django 4.2.7 on 2026-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('Own', 'Own Category')], default='C', max_length=10),
        ),
    ]
