# Generated by Django 5.1.4 on 2026-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_resumeemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
