# Generated by Django 5.0.6 on 2026-06-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeemaillog',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
