# Generated by Django 5.0.6 on 2026-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_resumeemaillog_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeemaillog',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
