# Generated by Django 4.2.7 on 2026-05-22 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
