# Generated by Django 5.0.6 on 2026-07-02 11:34

import apps.applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_offer_letter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.applications.models.get_offer_letter_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png']), apps.applications.models.validate_offer_letter_signature, apps.applications.models.validate_offer_letter_size]),
        ),
    ]
