# Generated by Django 4.2.7 on 2026-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_offer_letter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
