# Generated by Django 4.2.7 on 2026-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_letter_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_status',
            field=models.CharField(choices=[('pending_upload', 'Pending Upload'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_upload', max_length=20),
        ),
    ]
