# Generated by Django 4.2.7 on 2026-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('3rd', '3rd Year'), ('4th', '4th Year')], max_length=10, null=True),
        ),
    ]
