# Generated by Django 5.0.6 on 2026-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='created_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvuploadlog',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
    ]
