# Generated by Django 4.2.7 on 2026-06-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_created_updated_count_to_csvuploadlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentlearningassignment',
            unique_together=set(),
        ),
    ]
