# Generated by Django 4.2.7 on 2026-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_placements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_resumes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_students',
            field=models.BooleanField(default=False),
        ),
    ]
