# Generated by Django 5.0.6 on 2026-07-08 08:49

import uuid
from django.db import migrations, models


def seed_default_features(apps, schema_editor):
    StudentFeatureConfig = apps.get_model('core', 'StudentFeatureConfig')
    default_features = [
        {
            "feature_key": "mock-interview",
            "display_name": "Mock Interview",
            "description": "AI-driven mock interview feedback system",
        },
        {
            "feature_key": "resumes",
            "display_name": "My Resumes",
            "description": "Student resume builder and manager",
        },
        {
            "feature_key": "jobs",
            "display_name": "Jobs",
            "description": "Placement job listings and eligibility checker",
        },
        {
            "feature_key": "internships",
            "display_name": "Internships",
            "description": "Placement internship listings",
        },
        {
            "feature_key": "job-feed",
            "display_name": "Job Feed",
            "description": "External scraped job listings feed",
        },
        {
            "feature_key": "saved-jobs",
            "display_name": "Saved Jobs",
            "description": "Saved job postings list",
        },
        {
            "feature_key": "assignments",
            "display_name": "Assignments",
            "description": "Student learning assignments",
        },
        {
            "feature_key": "sessions",
            "display_name": "My Sessions",
            "description": "Zoom class/session schedules",
        },
        {
            "feature_key": "north-star",
            "display_name": "Project North Star",
            "description": "North star metric status and dashboard link",
        },
    ]
    for feat in default_features:
        StudentFeatureConfig.objects.get_or_create(
            feature_key=feat["feature_key"],
            defaults={
                "display_name": feat["display_name"],
                "description": feat["description"],
                "is_enabled": True,
                "allowed_departments": []
            }
        )


def remove_seeded_features(apps, schema_editor):
    StudentFeatureConfig = apps.get_model('core', 'StudentFeatureConfig')
    StudentFeatureConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentlearningassignment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('allowed_departments', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'student_feature_configs',
                'ordering': ['display_name'],
            },
        ),
        migrations.RunPython(seed_default_features, remove_seeded_features),
    ]

