# Generated by Django 4.2.7 on 2026-05-19 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_can_manage_placements_user_can_manage_resumes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClickLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.URLField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_click_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
