# Generated by Django 5.0.6 on 2026-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentfeatureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeatureconfig',
            name='allowed_years',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
