# Generated by Django 5.0.6 on 2026-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentfeatureconfig_allowed_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeatureconfig',
            name='allowed_courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
