# Generated by Django 4.2.7 on 2026-05-22 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_externalclicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlogs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='training_attendance',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
