# Generated by Django 4.2.7 on 2026-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_backlogs_count_student_training_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclicklog',
            name='is_marked_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalclicklog',
            name='marked_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

