# Generated by Django 4.2.7 on 2026-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentfeatureconfig_allowed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvuploadlog',
            name='emails_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
