# Generated by Django 4.2.30 on 2026-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_csvuploadlog_emails_sent_csvuploadlog_emails_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='sent_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='csvuploadlog',
            name='sent_emails_count',
            field=models.IntegerField(default=0),
        ),
    ]
