# Generated by Django 5.2.8 on 2026-06-02 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_is_category_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('min_cgpa', models.FloatField(default=0.0)),
                ('min_attendance', models.FloatField(default=0.0)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('min_training_attendance', models.FloatField(default=0.0)),
                ('score_threshold', models.IntegerField(default=3)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'placement_categories',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
