# Generated by Django 4.2.30 on 2026-07-22 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_csvuploadlog_sent_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('api_key_used', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email_used', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'sent_email_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
