# Generated by Django 4.2.30 on 2026-08-27 12:07

from django.db import migrations, models


def set_exit_status_for_sem_6(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    Student.objects.filter(semester=6).update(status='exited_3yr')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sentemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('exited_3yr', '3-Year Exit'), ('graduated_4yr', '4-Year Graduate')], db_index=True, default='active', help_text='Current academic/placement status of the student.', max_length=20),
        ),
        migrations.RunPython(set_exit_status_for_sem_6),
    ]
