# Generated by Django 4.2.7 on 2026-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_placementcategory_alter_student_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacementCategory',
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('Own', 'Own Category')], max_length=10, null=True),
        ),
    ]
