# Generated by Django 4.2.7 on 2026-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_placementcategory_alter_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclicklog',
            name='click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='externalclicklog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
