# Generated by Django 4.2.7 on 2026-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_learning_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_assignments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_clicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
