# Generated by Django 5.2.8 on 2026-06-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_can_manage_assignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upload_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to='core.csvuploadlog'),
        ),
        migrations.AlterField(
            model_name='csvuploadlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='success', max_length=20),
        ),
    ]
